sonar.projectKey=railsinfra_users
sonar.organization=railsinfra

sonar.projectName=users
sonar.projectVersion=0.1.0

sonar.sources=src

sonar.exclusions=target/**,.sqlx/**

sonar.sourceEncoding=UTF-8
